import type { Beat, DrumKit } from "./types";

export const beats: Beat[] = [
  {
    id: "beat-1",
    title: "Midnight Trap",
    genre: "Trap",
    bpm: 140,
    key: "C minor",
    mood: "Dark",
    audioUrl: "/audio/midnight-trap.mp3",
    imageUrl: "/images/beats/midnight-trap.jpg",
    tags: ["trap", "dark", "808"],
    licenses: [
      { id: "b1-basic", name: "Basic", price: 35, format: "MP3", streams: "100K streams", description: "Non-exclusive MP3 lease" },
      { id: "b1-premium", name: "Premium", price: 99, format: "WAV + Stems", streams: "500K streams", description: "Non-exclusive WAV + tracked stems" },
      { id: "b1-exclusive", name: "Exclusive", price: 499, format: "WAV + Stems", streams: "Unlimited", description: "Full exclusive rights — removed from store" },
    ],
  },
  {
    id: "beat-2",
    title: "Golden Hour",
    genre: "R&B",
    bpm: 92,
    key: "F major",
    mood: "Melodic",
    audioUrl: "/audio/golden-hour.mp3",
    imageUrl: "/images/beats/golden-hour.jpg",
    tags: ["rnb", "melodic", "soulful"],
    licenses: [
      { id: "b2-basic", name: "Basic", price: 40, format: "MP3", streams: "100K streams", description: "Non-exclusive MP3 lease" },
      { id: "b2-premium", name: "Premium", price: 110, format: "WAV + Stems", streams: "500K streams", description: "Non-exclusive WAV + tracked stems" },
      { id: "b2-exclusive", name: "Exclusive", price: 599, format: "WAV + Stems", streams: "Unlimited", description: "Full exclusive rights" },
    ],
  },
  {
    id: "beat-3",
    title: "Street Anthem",
    genre: "Hip-Hop",
    bpm: 88,
    key: "G minor",
    mood: "Hard",
    audioUrl: "/audio/street-anthem.mp3",
    imageUrl: "/images/beats/street-anthem.jpg",
    tags: ["hiphop", "hard", "boom bap"],
    licenses: [
      { id: "b3-basic", name: "Basic", price: 30, format: "MP3", streams: "100K streams", description: "Non-exclusive MP3 lease" },
      { id: "b3-premium", name: "Premium", price: 85, format: "WAV + Stems", streams: "500K streams", description: "Non-exclusive WAV + tracked stems" },
      { id: "b3-exclusive", name: "Exclusive", price: 399, format: "WAV + Stems", streams: "Unlimited", description: "Full exclusive rights" },
    ],
  },
];

export const drumKits: DrumKit[] = [
  {
    id: "kit-1",
    name: "Luchi Essentials Vol. 1",
    genre: "Hip-Hop / Trap",
    description: "The go-to kit for producers who want that hard-hitting, studio-quality sound straight out the box. Crafted from real sessions, every sample in this kit has been used in professional recordings.",
    price: 29.99,
    sampleCount: 150,
    formats: ["WAV", "24-bit"],
    tags: ["trap", "hip-hop", "808s", "hard"],
    popular: true,
    includes: ["50 Drum Hits", "30 808s & Bass", "25 Hi-Hats & Cymbals", "25 Snares & Claps", "20 FX & Transitions"],
  },
  {
    id: "kit-2",
    name: "Street Sessions Kit",
    genre: "Boom Bap / Hip-Hop",
    description: "Raw, gritty, and soulful. This kit pulls from the classic boom bap era and flips it for today's sound. Perfect for producers who want that East Coast feel with a modern edge.",
    price: 24.99,
    sampleCount: 120,
    formats: ["WAV", "24-bit"],
    tags: ["boom bap", "hip-hop", "soul", "east coast"],
    includes: ["40 Drum Hits", "20 Bass Hits", "25 Hi-Hats", "20 Snares & Claps", "15 Vinyl Breaks & FX"],
  },
  {
    id: "kit-3",
    name: "Cinematic Luchi Pack",
    genre: "R&B / Melodic",
    description: "Smooth, atmospheric, and cinematic. Built for R&B, melodic trap, and soul-influenced production. Every sound is warm, polished, and ready to sit perfectly in a mix.",
    price: 34.99,
    sampleCount: 180,
    formats: ["WAV", "24-bit"],
    tags: ["r&b", "melodic", "soul", "cinematic"],
    popular: false,
    includes: ["50 Drum Hits", "35 Melodic Percussion", "30 Hi-Hats & Rides", "35 Snares & Rimshots", "30 Ambience & FX"],
  },
  {
    id: "kit-4",
    name: "Producer Bundle",
    genre: "All Genres",
    description: "All three kits combined into one power bundle. Everything you need across Hip-Hop, Trap, Boom Bap, R&B, and beyond — at a price that makes sense for serious producers.",
    price: 69.99,
    sampleCount: 450,
    formats: ["WAV", "24-bit"],
    tags: ["bundle", "all genres", "trap", "r&b", "boom bap"],
    popular: false,
    includes: ["All 450+ Samples", "Luchi Essentials Vol. 1", "Street Sessions Kit", "Cinematic Luchi Pack", "Free Updates"],
  },
];
